on:
  push:
    tags:
      - 'v*'
name: Publish to the Factorio mod portal
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish mod
      uses: Penguin-Spy/factorio-mod-portal-publish@fix-git-exec
      with:
        factorio-api-key: ${{ secrets.FACTORIO_MOD_API_KEY }}